"""occupancy history

Revision ID: 70fe8fd155d6
Revises: 8c233c38fd9d
Create Date: 2026-10-10 22:20:11.891344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fe8fd155d6'
down_revision: Union[str, Sequence[str], None] = '8c233c38fd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy_history',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('simulated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('people >= 0', name=op.f('ck_occupancy_history_people_not_negative')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_occupancy_history_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'slot_start', name=op.f('pk_occupancy_history'))
    )
    op.create_index('ix_check_ins_institution_started', 'check_ins', ['institution_id', 'started_at'], unique=False)
    op.add_column('institutions', sa.Column('history_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'history_until')
    op.drop_index('ix_check_ins_institution_started', table_name='check_ins')
    op.drop_table('occupancy_history')
    # ### end Alembic commands ###
