"""counting since

Revision ID: 5c0a6b7e93cc
Revises: 70fe8fd155d6
Create Date: 2026-10-10 22:43:44.544161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0a6b7e93cc'
down_revision: Union[str, Sequence[str], None] = '70fe8fd155d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('counting_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'counting_since')
    # ### end Alembic commands ###
